### ISSUE TITLE
Running pkldoc Fails with `NullPointerException: uri.path must not be null`

### ISSUE THREAD

**Issue by jamesward** [apple/pkl#18]
```
./gradlew pkldoc
Starting a Gradle Daemon, 1 busy and 3 incompatible Daemons could not be reused, use --status for details

> Task :pkl-core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :stdlib:pkldoc
An unexpected error has occurred. Would you mind filing a bug report?

java.lang.NullPointerException: uri.path must not be null
        at org.pkl.doc.CliDocGenerator.doRun(CliDocGenerator.kt:237)
        at org.pkl.commons.cli.CliCommand.run(CliCommand.kt:45)
        at org.pkl.doc.DocCommand.run(Main.kt:71)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.pkl.doc.Main$main$1.invoke(Main.kt:36)
        at org.pkl.doc.Main$main$1.invoke(Main.kt:36)
        at org.pkl.commons.cli.CliMainKt.cliMain(CliMain.kt:31)
        at org.pkl.doc.Main.main(Main.kt:36)
```

**Comment by bioball** [comment]
Ah, this is an out-dated task; all pkldoc generation happens in https://github.com/apple/pkl-package-docs.

We should just take this task out.
