### ISSUE TITLE
[build-stderr] Caused by: java.lang.IllegalArgumentException: `0.27.0-dev+` could not be parsed as a semantic version number.

### ISSUE THREAD

**Issue by VikzSharma** [apple/pkl#667]
Hi ,
Getting this error while building : 

[2024-10-03 23:50:03] [build-stdout] > Task :pkl-core:jar
[2024-10-03 23:50:03] [build-stdout] > Task :pkl-core:javadocJar
[2024-10-03 23:50:04] [build-stdout] > Task :pkl-core:sourcesJar
[2024-10-03 23:50:04] [build-stdout] > Task :pkl-core:assemble
[2024-10-03 23:50:04] [build-stdout] > Task :pkl-core:spotlessAntlr4 FROM-CACHE
[2024-10-03 23:50:04] [build-stdout] > Task :pkl-core:spotlessAntlr4Check UP-TO-DATE
[2024-10-03 23:50:04] [build-stdout] > Task :pkl-config-java:shadowJar FROM-CACHE
[2024-10-03 23:50:05] [build-stdout] > Task :pkl-core:spotlessJava FROM-CACHE
[2024-10-03 23:50:05] [build-stdout] > Task :pkl-core:spotlessJavaCheck UP-TO-DATE
[2024-10-03 23:50:05] [build-stdout] > Task :pkl-config-java:generateTestConfigClasses FAILED
[2024-10-03 23:50:05] [build-stderr] Exception in thread "main" java.lang.ExceptionInInitializerError
[2024-10-03 23:50:05] [build-stderr] 	at org.pkl.codegen.java.PklJavaCodegenCommand.<init>(Main.kt:40)
[2024-10-03 23:50:05] [build-stderr] 	at org.pkl.codegen.java.Main$main$1.invoke(Main.kt:34)
[2024-10-03 23:50:05] [build-stderr] 	at org.pkl.codegen.java.Main$main$1.invoke(Main.kt:34)
[2024-10-03 23:50:05] [build-stderr] 	at org.pkl.commons.cli.CliMainKt.cliMain(CliMain.kt:33)
[2024-10-03 23:50:05] [build-stderr] 	at org.pkl.codegen.java.Main.main(Main.kt:34)
[2024-10-03 23:50:05] [build-stderr] Caused by: java.lang.IllegalArgumentException: `0.27.0-dev+` could not be parsed as a semantic version number.
[2024-10-03 23:50:05] [build-stderr] 	at org.pkl.core.Version.parse(Version.java:90)
[2024-10-03 23:50:05] [build-stderr] 	at org.pkl.core.Release.<clinit>(Release.java:48)
[2024-10-03 23:50:05] [build-stderr] 	... 5 more
[2024-10-03 23:50:05] [build-stdout] > Task :spotlessKotlinGradle FROM-CACHE
[2024-10-03 23:50:09] [build-stdout] > Task :pkl-core:spotlessKotlin
[2024-10-03 23:50:12] [build-stderr] FAILURE: Build failed with an exception.
[2024-10-03 23:50:12] [build-stdout] > Task :pkl-cli:compileJava
[2024-10-03 23:50:12] [build-stderr] * What went wrong:
[2024-10-03 23:50:12] [build-stdout] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
[2024-10-03 23:50:12] [build-stderr] Execution failed for task ':pkl-config-java:generateTestConfigClasses'.
[2024-10-03 23:50:12] [build-stderr] > Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 1
[2024-10-03 23:50:12] [build-stderr] * Try:
[2024-10-03 23:50:12] [build-stderr] > Run with --stacktrace option to get the stack trace.
[2024-10-03 23:50:12] [build-stderr] > Run with --info or --debug option to get more log output.
[2024-10-03 23:50:12] [build-stderr] > Run with --scan to get full insights.
[2024-10-03 23:50:12] [build-stdout] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[2024-10-03 23:50:12] [build-stderr] > Get more help at https://help.gradle.org.
[2024-10-03 23:50:12] [build-stdout] For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
[2024-10-03 23:50:12] [build-stderr] BUILD FAILED in 19s

**Comment by bioball** [comment]
Looks like it's missing the commit sha. How are you building this? Did you clone the repo and build, or do something else?
